### ISSUE TITLE
gradle isn't working for me

### ISSUE THREAD

**Issue by wlund-pivotal** [appsuite/tcserver-spring-boot-samples#2]
I'm getting this error when I try to import the project:

> Could not find property 'pivotal_maven_repo_username' on root project 'spring-boot-starter-tcserver-example'.

I put the property in application.properties and .m2/settings.xml although hope I didn't need the latter, and can't get past the error. What am I missing?

**Comment by wlund-pivotal** [comment]
It looks like an authorization problem.  When I try:

mvn install

from the command line I get:

Failed to exectue goal on project spring-boot-starter-tcserver-example: Could not resolve dependencies for project com.springsource.tcruntime.embedded.bootexample:spring-boot-starter-tcserver-example:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.springsource ... etc.

**Comment by wesschlichter** [comment]
Hi Wayne,

Thanks for the feedback.

For gradle: 
You need to create a gradle.properties file which contains your username and password fromt he Commercial Maven Repository. This was buried as a comment in the build.gradle file which I realize may not have been obvious as such I have updated the README to reflect this also.

For maven:
Which version of maven are you using? Older versions of maven don't work with the Pivotal Commercial Maven Repository's authentication requirements. Spring-boot requires 3.2 and we have mirrored that requirement.  Also have you updated your ~/.m2/settings.xml with your username/password from the Pivotal Commercial Maven Repository as explained in the README?  There are two server elements which both need to be added.
